image: Visual Studio 2019

environment:
  NODEJS_VERSION: "10.15.0"
  HEROKU_API_KEY:
    secure: 1lPeSjPcA6p/DitsGAWrS7C6sWAleieEmoS4Lmg7DwjVYYEfQD6iK2aVvLA0nO5Z
  IMAGE_NAME: registry.heroku.com/gbs
  IMAGE_TAG: dev

cache:
 - "%LOCALAPPDATA%\\Yarn"
 - node_modules

install:
  - ps: Install-Product node $env:NODEJS_VERSION

build_script:
  - yarn build

before_build:
  - yarn
  - yarn lint

after_build:
  - docker login --username=_ --password=$($env:HEROKU_API_KEY) registry.heroku.com
  - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
  - docker push ${IMAGE_NAME}:${IMAGE_TAG}