environment:
  nodejs_version: "10.15.0"

cache:
 - "%LOCALAPPDATA%\\Yarn"
 - node_modules

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - yarn build

before_build:
  - yarn
  - yarn lint

artifacts:
  - path: dist
  - path: public