image: Visual Studio 2017

environment:
  NODEJS_VERSION: "10.15.0"
  # HEROKU_LOGIN: tmvan.1903@gmail.com
  # HEROKU_APP_NAME: green-bean-shop
  # HEROKU_API_KEY:
  #   secure: 8KnabZ+MuT/v+wYSzbPPNELYX5ZZxNhfRLv01rEwkvjHZm6ejJiEbPYAKfHZ1fvz
  # IMAGE_NAME: registry.heroku.com/gbs
  # IMAGE_TAG: dev

cache:
 - "%LOCALAPPDATA%\\Yarn"
 - node_modules

install:
  - ps: Install-Product node $env:NODEJS_VERSION

build_script:
  - yarn build

before_build:
  - yarn
  - yarn lint

# after_build:
#   - heroku login
#   - heroku container:login
#   - heroku container:push web
#   - heroku container:release web